# theme: jekyll-theme-minimal
theme: minima
title: 遊牧空間
author:
  name: "integmath"
description: abc

minima:
 date_format: "%Y-%m-%d"
header_pages:
- note.md
- marginalia.md

social_links:
 twitter: integmath