# theme: jekyll-theme-minimal
title: 遊牧空間
author:
  name: "integmath"
description: > 
  abc

show_excerpts: false

minima:
 date_format: "%Y-%m-%d"

header_pages:
- note.md
- marginalia.md

minima:
 social_links:
  twitter: integmath

theme: minima